import 'model.dart';

List<CustomerData> sampleUserData = [
  CustomerData(
    name: 'John Smith',
    receiverName: 'Coffee Shop',
    location: 'Chennai Central',
    frequency: 20,
    dateTime: '2-May-2024',
  ),
  CustomerData(
    name: 'Emily Jones',
    receiverName: 'Gym',
    location: 'Perungalatur',
    frequency: 3,
    dateTime: '2-May-2024',
  ),
  CustomerData(
    name: 'Charles Johnson',
    receiverName: 'Grocery Store',
    location: 'Kilpauk',
    frequency: 22,
    dateTime: '2-May-2024',
  ),
  CustomerData(
    name: 'Matthew Gray',
    receiverName: 'Gas Station',
    location: 'Aminjikarai',
    frequency: 9,
    dateTime: '2-May-2024',
  ),
  CustomerData(
    name: 'Ronald Walker',
    receiverName: 'Hospital',
    location: 'Perungalatur',
    frequency: 5,
    dateTime: '2-May-2024',
  ),
  CustomerData(
    name: 'Andrew Garcia',
    receiverName: 'ATM',
    location: 'IOC',
    frequency: 9,
    dateTime: '2-May-2024',
  ),
  CustomerData(
    name: 'Jane Doe',
    receiverName: 'Supermarket',
    location: 'T Nagar',
    frequency: 8,
    dateTime: '19-Jan-2024',
  ),
  CustomerData(
    name: 'Richard Lewis',
    receiverName: 'Bakery',
    location: 'Triplicane',
    frequency: 5,
    dateTime: '19-Jan-2024',
  ),
  CustomerData(
    name: 'Joseph Garcia',
    receiverName: 'Bank',
    location: 'Alwarpet',
    frequency: 6,
    dateTime: '19-Jan-2024',
  ),
  CustomerData(
    name: 'Benjamin Lewis',
    receiverName: 'University',
    location: 'Anna Nagar',
    frequency: 7,
    dateTime: '19-Jan-2024',
  ),
  CustomerData(
    name: 'Steven Miller',
    receiverName: 'Streaming Service',
    location: 'somalia',
    frequency: 8,
    dateTime: '19-Jan-2024',
  ),
  CustomerData(
    name: 'Richard Lewis',
    receiverName: 'Bakery',
    location: 'Triplicane',
    frequency: 4,
    dateTime: '19-Jan-2024',
  ),
  CustomerData(
    name: 'Joseph Garcia',
    receiverName: 'Bank',
    location: 'Alwarpet',
    frequency: 5,
    dateTime: '19-Jan-2024',
  ),
  CustomerData(
    name: 'Steven Miller',
    receiverName: 'Gas Station',
    location: 'Aminjikarai',
    frequency: 5,
    dateTime: '19-Jan-2024',
  ),
  CustomerData(
    name: 'Elizabeth Brown',
    receiverName: 'Bakery',
    location: 'Triplicane',
    frequency: 3,
    dateTime: '19-Jan-2024',
  ),
  CustomerData(
    name: 'Joseph Garcia',
    receiverName: 'Hospital',
    location: 'Perungalatur',
    frequency: 4,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Christopher Rodriguez',
    receiverName: 'Delivery Service',
    location: 'Mannady',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Robert Brown',
    receiverName: 'Electronics Store',
    location: 'Tambaram',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Lisa Garcia',
    receiverName: 'Airport',
    location: 'Meenambakkam',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Barbara Moore',
    receiverName: 'Florist',
    location: 'Arumbakkam',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Lisa Garcia',
    receiverName: 'Hotel (Mount Road)',
    location: 'Mount Road',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Barbara Moore',
    receiverName: 'Hospital',
    location: 'Perungalatur',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Christopher Rodriguez',
    receiverName: 'Hospital',
    location: 'Perungalatur',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Joseph Garcia',
    receiverName: 'Hospital',
    location: 'Perungalatur',
    frequency: 4,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Christopher Rodriguez',
    receiverName: 'Delivery Service',
    location: 'Mannady',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Robert Brown',
    receiverName: 'Electronics Store',
    location: 'Tambaram',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Lisa Garcia',
    receiverName: 'Airport',
    location: 'Meenambakkam',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Barbara Moore',
    receiverName: 'Florist',
    location: 'Arumbakkam',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Lisa Garcia',
    receiverName: 'Hotel (Mount Road)',
    location: 'Mount Road',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Barbara Moore',
    receiverName: 'Hospital',
    location: 'Perungalatur',
    frequency: 2,
    dateTime: '25-Feb-2024',
  ),
  CustomerData(
    name: 'Benjamin Lewis',
    receiverName: 'University',
    location: 'Anna Nagar',
    frequency: 7,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Steven Miller',
    receiverName: 'Streaming Service',
    location: 'somalia',
    frequency: 8,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Richard Lewis',
    receiverName: 'Bakery',
    location: 'Triplicane',
    frequency: 4,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Joseph Garcia',
    receiverName: 'Bank',
    location: 'Alwarpet',
    frequency: 5,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Steven Miller',
    receiverName: 'Gas Station',
    location: 'Aminjikarai',
    frequency: 5,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Elizabeth Brown',
    receiverName: 'Bakery',
    location: 'Triplicane',
    frequency: 3,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Benjamin Lewis',
    receiverName: 'University',
    location: 'Anna Nagar',
    frequency: 7,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Steven Miller',
    receiverName: 'Streaming Service',
    location: 'somalia',
    frequency: 8,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Richard Lewis',
    receiverName: 'Bakery',
    location: 'Triplicane',
    frequency: 4,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Joseph Garcia',
    receiverName: 'Bank',
    location: 'Alwarpet',
    frequency: 5,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Steven Miller',
    receiverName: 'Gas Station',
    location: 'Aminjikarai',
    frequency: 5,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Elizabeth Brown',
    receiverName: 'Bakery',
    location: 'Triplicane',
    frequency: 3,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'William Hernandez',
    receiverName: 'Streaming Service',
    location: 'somalia',
    frequency: 7,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Susan Clark',
    receiverName: 'Bank',
    location: 'Alwarpet',
    frequency: 5,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'James Brown',
    receiverName: 'Streaming Service',
    location: 'somalia',
    frequency: 6,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Sarah Jones',
    receiverName: 'Gas Station',
    location: 'Aminjikarai',
    frequency: 3,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Richard Lewis',
    receiverName: 'Streaming Service',
    location: 'somalia',
    frequency: 4,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Matthew Gray',
    receiverName: 'Bank',
    location: 'Alwarpet',
    frequency: 3,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Sarah Jones',
    receiverName: 'somalia Store',
    location: 'Mannady',
    frequency: 3,
    dateTime: '8-Mar-2024',
  ),
  CustomerData(
    name: 'Elizabeth Brown',
    receiverName: 'Bank',
    location: 'Alwarpet',
    frequency: 2,
    dateTime: '29-Mar-2024',
  ),
  CustomerData(
    name: 'Sarah Lee',
    receiverName: 'Restaurant',
    location: 'Anna Nagar',
    frequency: 5,
    dateTime: '28-Mar-2024',
  ),
  CustomerData(
    name: 'Elizabeth Williams',
    receiverName: 'Pharmacy',
    location: 'Egmore',
    frequency: 8,
    dateTime: '28-Mar-2024',
  ),
  CustomerData(
    name: 'James Brown',
    receiverName: 'Hotel',
    location: 'Triplicane',
    frequency: 4,
    dateTime: '28-Mar-2024',
  ),
  CustomerData(
    name: 'David Williams',
    receiverName: 'somalia Store',
    location: 'Mannady',
    frequency: 5,
    dateTime: '28-Mar-2024',
  ),
  CustomerData(
    name: 'Charles Gray',
    receiverName: 'Electronics Store',
    location: 'Tambaram',
    frequency: 3,
    dateTime: '28-Mar-2024',
  ),
  CustomerData(
    name: 'Elizabeth Williams',
    receiverName: 'Pharmacy',
    location: 'Egmore',
    frequency: 7,
    dateTime: '28-Mar-2024',
  ),
  CustomerData(
    name: 'Alice Miller',
    receiverName: 'Movie Theater',
    location: 'Velachery',
    frequency: 7,
    dateTime: '30-Apr-2024',
  ),
  CustomerData(
    name: 'David Miller (Monthly End)',
    receiverName: 'Rent Payment',
    location: 'somalia',
    frequency: 2,
    dateTime: '30-Apr-2024',
  ),
  CustomerData(
    name: 'Christopher Rodriguez (Monthly End)',
    receiverName: 'Electricity Bill',
    location: 'somalia',
    frequency: 2,
    dateTime: '30-Apr-2024',
  ),
  CustomerData(
    name: 'Sarah Jones',
    receiverName: 'Delivery Service',
    location: 'Mannady',
    frequency: 6,
    dateTime: '30-Apr-2024',
  ),
  CustomerData(
    name: 'Matthew Gray',
    receiverName: 'Gas Station',
    location: 'Aminjikarai',
    frequency: 8,
    dateTime: '30-Apr-2024',
  ),
  CustomerData(
    name: 'Christopher Rodriguez',
    receiverName: 'Gym',
    location: 'Perungalatur',
    frequency: 4,
    dateTime: '30-Apr-2024',
  ),
  CustomerData(
    name: 'Emily Walker',
    receiverName: 'Delivery Service',
    location: 'Mannady',
    frequency: 4,
    dateTime: '30-Apr-2024',
  ),
  CustomerData(
    name: 'Lisa Garcia',
    receiverName: 'Delivery Service',
    location: 'Mannady',
    frequency: 3,
    dateTime: '30-Apr-2024',
  ),
  CustomerData(
    name: 'Andrew Garcia',
    receiverName: 'Gym',
    location: 'Perungalatur',
    frequency: 6,
    dateTime: '30-Apr-2024',
  ),
  CustomerData(
    name: 'David Miller',
    receiverName: 'Gas Station',
    location: 'Aminjikarai',
    frequency: 6,
    dateTime: '30-Apr-2024',
  ),
  CustomerData(
    name: 'Andrew Garcia',
    receiverName: 'Streaming Service',
    location: 'somalia',
    frequency: 6,
    dateTime: '30-Apr-2024',
  ),
  CustomerData(
    name: 'Jane Doe',
    receiverName: 'Supermarket',
    location: 'T Nagar',
    frequency: 8,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'Richard Lewis',
    receiverName: 'Bakery',
    location: 'Triplicane',
    frequency: 5,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'Joseph Garcia',
    receiverName: 'Bank',
    location: 'Alwarpet',
    frequency: 6,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'Benjamin Lewis',
    receiverName: 'University',
    location: 'Anna Nagar',
    frequency: 7,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'Steven Miller',
    receiverName: 'Streaming Service',
    location: 'somalia',
    frequency: 8,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'Richard Lewis',
    receiverName: 'Bakery',
    location: 'Triplicane',
    frequency: 4,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'Joseph Garcia',
    receiverName: 'Bank',
    location: 'Alwarpet',
    frequency: 5,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'Steven Miller',
    receiverName: 'Gas Station',
    location: 'Aminjikarai',
    frequency: 5,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'Elizabeth Brown',
    receiverName: 'Bakery',
    location: 'Triplicane',
    frequency: 3,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'William Hernandez',
    receiverName: 'Streaming Service',
    location: 'somalia',
    frequency: 7,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'Susan Clark',
    receiverName: 'Bank',
    location: 'Alwarpet',
    frequency: 5,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'James Brown',
    receiverName: 'Streaming Service',
    location: 'somalia',
    frequency: 6,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'Sarah Jones',
    receiverName: 'Gas Station',
    location: 'Aminjikarai',
    frequency: 3,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'Richard Lewis',
    receiverName: 'Streaming Service',
    location: 'somalia',
    frequency: 4,
    dateTime: '29-Apr-2024',
  ),
  CustomerData(
    name: 'Matthew Gray',
    receiverName: 'Bank',
    location: 'Alwarpet',
    frequency: 3,
    dateTime: '29-Apr-2024',
  ),
];
